### ISSUE TITLE
VersionUrlError

### ISSUE THREAD

**Issue by Asuratomique** [zaironjacobs/get-chrome-driver#3]
Hello, I have this problem when downloading my chrome driver with your tool. Same problem with Gecko driver ! InvalidURL. I have the two good versions of browser. Thanks in advance

-> Téléchargement du driver pour Google Chrome en cours...
Traceback (most recent call last):
  File "C:\Users\hugog\OneDrive\Bureau\Rousseau-main\Rousseau-main\main.py", line 174, in <module>
    main()
  File "C:\Users\hugog\OneDrive\Bureau\Rousseau-main\Rousseau-main\main.py", line 141, in main
    check_driver("chromedriver")
  File "C:\Users\hugog\OneDrive\Bureau\Rousseau-main\Rousseau-main\main.py", line 100, in check_driver
    download_driver(driver_name)
  File "C:\Users\hugog\OneDrive\Bureau\Rousseau-main\Rousseau-main\main.py", line 110, in download_driver
    get_driver.download_stable_version(extract=True, output_path='./drivers/')
  File "C:\Users\hugog\AppData\Local\Programs\Python\Python311\Lib\site-packages\get_chrome_driver\get_driver.py", line 151, in download_stable_version
    self.download_version(version=version, output_path=output_path, extract=extract)
  File "C:\Users\hugog\AppData\Local\Programs\Python\Python311\Lib\site-packages\get_chrome_driver\get_driver.py", line 196, in download_version
    url = self.version_url(version)
          ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\hugog\AppData\Local\Programs\Python\Python311\Lib\site-packages\get_chrome_driver\get_driver.py", line 109, in version_url
    self.__check_if_url_is_valid(url)
  File "C:\Users\hugog\AppData\Local\Programs\Python\Python311\Lib\site-packages\get_chrome_driver\get_driver.py", line 207, in __check_if_url_is_valid
    raise VersionUrlError('Invalid url')
get_chrome_driver.exceptions.VersionUrlError: Invalid url
PS C:\Users\hugog\OneDrive\Bureau\Rousseau-main\Rousseau-main>

**Comment by zaironjacobs** [comment]
Hello, do you have the latest version installed?

`pip install get-chrome-driver --upgrade`

**Comment by Asuratomique** [comment]
> Hello, do you have the latest version installed?
> 
> 
> 
> `pip install get-chrome-driver --upgrade`

Yes I did this : 

$ pip install -r requirements.txt

And I have this in requirements.txt : 

selenium==4.0.0
wget==3.2
get-chrome-driver
get-gecko-driver

**Comment by zaironjacobs** [comment]
Try adding

`get-chrome-driver>=1.3.9`

And then `pip install -r requirements.txt`

**Comment by Asuratomique** [comment]
> Try adding
> 
> 
> 
> `get-chrome-driver>=1.3.9`
> 
> 
> 
> And then `pip install -r requirements.txt`

I tried, but unfortunately I have the same error in the console.  When I look in AppData/Local/Programs/Python/Python311/lib/site-packages I have these folders:
![image](https://user-images.githubusercontent.com/118575159/204936324-cfb0dd7d-93d7-4fa5-a410-d8a73d805234.jpeg)

**Comment by zaironjacobs** [comment]
There was a behavior change with Enums in Python 3.11. This is now fixed in the versions below, works fine with previous python 3 versions also.

`get-chrome-driver>=1.3.10`
`get-gecko-driver>=1.3.10`

**Comment by Asuratomique** [comment]
> There was a behavior change with Enums in Python 3.11. This is now fixed in the tool versions below, works fine with previous python 3 versions (starting from 3.4) also.
> 
> `get-chrome-driver>=1.3.10` `get-gecko-driver>=1.3.10`

Great thank you very much it seems to have unlocked my problem even if it took me to another one. Can you maybe help me? otherwise I will mark this ticket as solved :) thanks again
https://stackoverflow.com/q/74637360/20652705

**Comment by zaironjacobs** [comment]
When you call the check_driver function, driver_name should be something like `chromedriver.exe`, you should include the extension.
